"""Report generator — outputs audit results in multiple formats."""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path

from jinja2 import Environment, FileSystemLoader

from .detector import DetectionResult, Vulnerability, Severity


def _severity_emoji(severity: Severity) -> str:
    return {
        Severity.CRITICAL: "🔴",
        Severity.HIGH: "🟠",
        Severity.MEDIUM: "🟡",
        Severity.LOW: "🔵",
        Severity.INFO: "ℹ️",
    }.get(severity, "❓")


def generate_markdown_report(
    sol_path: str,
    detection: DetectionResult,
    llm_vulns: list | None = None,
    chain_info: dict | None = None,
) -> str:
    """Generate a Markdown audit report."""
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    summary = detection.summary
    total = sum(summary.values())

    # Merge LLM re-evaluated vulns (if available) with Slither results
    vulns = llm_vulns if llm_vulns else detection.vulnerabilities

    lines = [
        f"# Mantle-Audit-AI 审计报告",
        f"",
        f"**项目**: `{Path(sol_path).name}`",
        f"**审计时间**: {now}",
        f"**总体评分**: {'⚠️ 需要修复' if total > 0 else '✅ 未发现漏洞'}",
        f"",
        f"---",
        f"",
        f"## 漏洞统计",
        f"",
        f"| 严重程度 | 数量 |",
        f"|---------|------|",
    ]

    for sev in [Severity.CRITICAL, Severity.HIGH, Severity.MEDIUM, Severity.LOW, Severity.INFO]:
        count = summary.get(sev.value, 0)
        lines.append(f"| {_severity_emoji(sev)} {sev.value} | {count} |")

    lines.extend(["", "---", "", "## 漏洞清单", ""])

    if not vulns:
        lines.append("未发现漏洞。")
    else:
        # Sort: Critical first
        order = {Severity.CRITICAL: 0, Severity.HIGH: 1, Severity.MEDIUM: 2, Severity.LOW: 3, Severity.INFO: 4}
        sorted_vulns = sorted(vulns, key=lambda v: order.get(v.severity, 5))

        for i, v in enumerate(sorted_vulns, start=1):
            lines.extend([
                f"### {_severity_emoji(v.severity)} [{v.vuln_id}] {v.check} ({v.severity.value})",
                f"",
                f"**位置**: `{v.file_path or 'N/A'}` L{v.line_start}",
                f"**置信度**: {v.confidence.value}",
                f"",
                f"**描述**:",
                f"{v.description}",
                f"",
            ])
            if v.attack_path:
                lines.extend([
                    f"**攻击路径**:",
                    f"{v.attack_path}",
                    f"",
                ])
            if v.recommendation:
                lines.extend([
                    f"**修复建议**:",
                    f"```solidity",
                    f"{v.recommendation}",
                    f"```",
                    f"",
                ])
            if v.is_mantle_specific:
                lines.append(f"🔗 **Mantle 生态特有风险**")
                lines.append("")
            lines.append("---")
            lines.append("")

    # Chain info
    if chain_info:
        lines.extend([
            "## 链上凭证",
            "",
            f"| 项目 | 值 |",
            f"|------|-----|",
            f"| IPFS CID | `{chain_info.get('ipfs_cid', 'N/A')}` |",
            f"| 交易哈希 | `{chain_info.get('tx_hash', 'N/A')}` |",
            f"| 审计 ID | `{chain_info.get('audit_id', 'N/A')}` |",
            f"| 区块号 | {chain_info.get('block_number', 'N/A')} |",
            "",
        ])

    lines.extend([
        "",
        "---",
        f"*Generated by Mantle-Audit-AI v0.1.0*",
    ])

    return "\n".join(lines)


def generate_json_report(
    sol_path: str,
    detection: DetectionResult,
    llm_vulns: list | None = None,
    chain_info: dict | None = None,
) -> str:
    """Generate a JSON audit report."""
    vulns = llm_vulns if llm_vulns else detection.vulnerabilities
    report = {
        "tool": "Mantle-Audit-AI",
        "version": "0.1.0",
        "file": sol_path,
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "summary": detection.summary,
        "vulnerabilities": [v.to_dict() for v in vulns],
        "errors": detection.errors,
    }
    if chain_info:
        report["chain"] = chain_info
    return json.dumps(report, indent=2, ensure_ascii=False)


def save_report(content: str, output_path: str) -> str:
    """Save report to file and return the path."""
    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)
    return str(path.absolute())
